export const iceBreakers = {
  en: [
    "What superpower would you pick?",
    "Most adventurous thing you've done?",
    "Dream travel destination?",
    "Favorite movie or TV show?",
    "Which historical figure would you meet?",
    "Most unusual job you've had?",
    "Skill you wish you could master instantly?",
    "Best advice you've ever gotten?",
    "Three people for your dream dinner party?",
    "Book that changed your life?",
    "Time travel: past or future?",
    "Most memorable gift ever?",
    "Whose life would you swap for a day?",
    "Coolest place you've visited?",
    "Dream pet?",
    "Favorite childhood memory?",
    "Language you'd love to speak?",
    "Weirdest food you've tried?",
    "Fictional character you'd be?",
    "Biggest life lesson so far?",
    "How much money would it take for you to eat a live spider?",
    "What's the weirdest thing you do when no one's watching?",
    "Most embarrassing thing you've googled?",
    "Worst lie you've told your parents?",
    "What conspiracy theory do you secretly believe?",
    "Most cringe thing you posted on social media?",
    "Weirdest place you've cried in public?",
    "What's your most irrational fear?",
    "Worst fashion phase you went through?",
    "Most awkward family dinner conversation?",
    "What would you do for $1000 right now?",
    "Strangest compliment you've received?",
    "Most embarrassing autocorrect fail?",
    "What's your weirdest habit?",
    "Worst excuse you've used to get out of plans?",
    "Most inappropriate time you've laughed?",
    "What's the dumbest way you've injured yourself?",
    "Most awkward encounter with a celebrity/crush?",
    "Weirdest food combination you actually enjoy?",
    "What's your most embarrassing childhood memory?",
    "Most ridiculous thing you've done for attention?",
    "What's your secret guilty pleasure?",
    "Worst pickup line you've used or received?",
    "Most awkward text you've sent to the wrong person?",
    "What would your browser history say about you?",
    "Most embarrassing thing you believed as a kid?",
    "What's your weirdest deal breaker in dating?",
    "Most cringe username you've ever had?",
    "Worst roommate story?",
    "What's the pettiest thing you've done?",
    "Most awkward elevator ride?",
    "What's your most embarrassing talent?",
    "Worst wardrobe malfunction?",
    "Most inappropriate crush you've had?",
    "What's the weirdest compliment you'd want to receive?",
    "Most awkward thing you've walked in on?",
    "What's your most embarrassing drunk story?",
    "Weirdest thing you've done to avoid someone?",
    "Most cringe thing you did to impress someone?",
    "What's your most embarrassing medical story?",
    "Worst date story?",
    "Most awkward thing your parents have said?",
    "What's the weirdest thing you've found attractive?",
    "Most embarrassing thing you've done at work?",
    "What's your most shameful binge-watch?",
    "Worst bathroom emergency in public?",
    "Most awkward misunderstanding?",
    "What's the stupidest thing you've cried about?",
    "Most embarrassing thing you've done while drunk?",
    "What's your weirdest turn-on?",
    "Complete: 'I once walked into a coffee shop and...'",
    "Describe your sex life using only movie titles",
    "Complete: 'My therapist would say I have issues with...'",
    "What's the worst possible superpower?",
    "Complete: 'Breaking news: Local person arrested for...'",
    "Pitch a terrible reality TV show in 10 words",
    "Complete: 'I'm not saying I'm Batman, but...'",
    "What's the weirdest thing you'd put on a pizza?",
    "Complete: 'My dating profile should really say...'",
    "Invent a useless app idea",
    "Complete: 'I'm banned from the grocery store because...'",
    "What's your porn star name? (first pet + street you grew up on)",
    "Complete: 'The real reason dinosaurs went extinct was...'",
    "Describe your life using only song titles",
    "Complete: 'At my funeral, please don't mention...'",
    "What's the most absurd news headline you can imagine?",
    "Complete: 'I told my parents I was studying, but actually...'",
    "Invent a new Olympic sport",
    "Complete: 'My neighbors think I'm weird because...'",
    "What would your warning label say?",
    "Complete: 'Breaking news: Local person ruins everything by...'",
    "Describe your cooking skills using only horror movie titles",
    "Complete: 'I pretend to be an adult, but secretly...'",
    "What's the worst possible name for a dating app?",
    "Complete: 'My browser history is probably concerning because...'",
    "Pitch a sequel to a movie that doesn't need one",
    "Complete: 'I thought I was being smooth, but...'",
    "What's your superhero name based on your biggest weakness?",
    "Complete: 'The aliens returned me because...'",
    "Describe your personality using only food",
    "Complete: 'My last words will probably be...'",
    "What's the worst possible fortune cookie message?",
    "Complete: 'I was today years old when I learned...'",
    "Invent a new phobia",
    "Complete: 'My autobiography would be called...'",
    "What's your stripper name? (favorite color + last thing you ate)",
    "Complete: 'I'm not drunk, I'm just...'",
    "Describe your love life using only restaurant chains",
    "Complete: 'My biggest flex is...'",
    "What's the worst possible pickup line using food?",
    "Complete: 'Google search: How to...'",
    "Pitch a crossover between two completely unrelated shows",
    "Complete: 'Dear diary, today I accidentally...'",
    "What's your villain origin story in 3 words?",
    "Complete: 'Plot twist: I'm actually...'",
    "Describe your morning routine using only chaos",
    "Complete: 'Instructions unclear, ended up...'",
    "What's the worst possible theme for a restaurant?",
    "Complete: 'My spirit animal is a... because...'",
  ],
  fr: [
    "Quel super-pouvoir choisirais-tu ?",
    "La chose la plus aventureuse que tu aies faite ?",
    "Destination de voyage de rêve ?",
    "Film ou série télé préférés ?",
    "Quelle personnalité historique aimerais-tu rencontrer ?",
    "Le travail le plus inhabituel que tu aies eu ?",
    "Compétence que tu aimerais maîtriser instantanément ?",
    "Le meilleur conseil que tu aies jamais reçu ?",
    "Trois personnes pour ton dîner de rêve ?",
    "Livre qui a changé ta vie ?",
    "Voyage dans le temps : passé ou futur ?",
    "Le cadeau le plus mémorable ?",
    "Avec qui échangerais-tu ta vie pendant une journée ?",
    "L'endroit le plus cool que tu aies visité ?",
    "Animal de compagnie de rêve ?",
    "Souvenir d'enfance préféré ?",
    "Langue que tu adorerais parler ?",
    "La nourriture la plus bizarre que tu aies goûtée ?",
    "Personnage fictif que tu aimerais être ?",
    "Plus grande leçon de vie jusqu'à présent ?",
    "Combien d'argent faudrait-il pour que tu manges une araignée vivante ?",
    "Quelle est la chose la plus bizarre que tu fais quand personne ne regarde ?",
    "La chose la plus embarrassante que tu aies cherchée sur Google ?",
    "Le pire mensonge que tu aies dit à tes parents ?",
    "Quelle théorie du complot crois-tu secrètement ?",
    "La chose la plus gênante que tu aies postée sur les réseaux sociaux ?",
    "L'endroit le plus bizarre où tu aies pleuré en public ?",
    "Quelle est ta peur la plus irrationnelle ?",
    "La pire phase vestimentaire que tu aies traversée ?",
    "La conversation de dîner de famille la plus gênante ?",
    "Que ferais-tu pour 1000€ maintenant ?",
    "Le compliment le plus étrange que tu aies reçu ?",
    "L'échec d'autocorrection le plus embarrassant ?",
    "Quelle est ta habitude la plus bizarre ?",
    "La pire excuse que tu aies utilisée pour annuler des plans ?",
    "Le moment le plus inapproprié où tu aies ri ?",
    "Quelle est la façon la plus stupide dont tu te sois blessé(e) ?",
    "La rencontre la plus gênante avec une célébrité/un béguin ?",
    "La combinaison de nourriture la plus bizarre que tu apprécies vraiment ?",
    "Quel est ton souvenir d'enfance le plus embarrassant ?",
    "La chose la plus ridicule que tu aies faite pour attirer l'attention ?",
    "Quel est ton plaisir coupable secret ?",
    "La pire phrase de drague que tu aies utilisée ou reçue ?",
    "Le texto le plus gênant que tu aies envoyé à la mauvaise personne ?",
    "Que dirait ton historique de navigation sur toi ?",
    "La chose la plus embarrassante que tu croyais enfant ?",
    "Quel est ton critère rédhibitoire le plus bizarre en amour ?",
    "Le nom d'utilisateur le plus gênant que tu aies eu ?",
    "Pire histoire de colocataire ?",
    "Quelle est la chose la plus mesquine que tu aies faite ?",
    "Le trajet en ascenseur le plus gênant ?",
    "Quel est ton talent le plus embarrassant ?",
    "Pire incident vestimentaire ?",
    "Le béguin le plus inapproprié que tu aies eu ?",
    "Quel est le compliment le plus bizarre que tu aimerais recevoir ?",
    "La chose la plus gênante sur laquelle tu sois tombé(e) ?",
    "Quelle est ton histoire d'ivresse la plus embarrassante ?",
    "La chose la plus bizarre que tu aies faite pour éviter quelqu'un ?",
    "La chose la plus gênante que tu aies faite pour impressionner quelqu'un ?",
    "Quelle est ton histoire médicale la plus embarrassante ?",
    "Pire histoire de rendez-vous ?",
    "La chose la plus gênante que tes parents aient dite ?",
    "Quelle est la chose la plus bizarre que tu aies trouvée attirante ?",
    "La chose la plus embarrassante que tu aies faite au travail ?",
    "Quel est ton binge-watching le plus honteux ?",
    "Pire urgence toilettes en public ?",
    "Le malentendu le plus gênant ?",
    "Quelle est la chose la plus stupide pour laquelle tu aies pleuré ?",
    "La chose la plus embarrassante que tu aies faite en étant ivre ?",
    "Quel est ton fantasme le plus bizarre ?",
    "Complète : 'Un jour, je suis entré(e) dans un café et...'",
    "Décris ta vie sexuelle en utilisant uniquement des titres de films",
    "Complète : 'Mon psy dirait que j'ai des problèmes avec...'",
    "Quel est le pire super-pouvoir possible ?",
    "Complète : 'Flash info : Une personne arrêtée pour...'",
    "Propose une émission de télé-réalité terrible en 10 mots",
    "Complète : 'Je ne dis pas que je suis Batman, mais...'",
    "Quelle est la chose la plus bizarre que tu mettrais sur une pizza ?",
    "Complète : 'Mon profil de rencontre devrait vraiment dire...'",
    "Invente une idée d'app inutile",
    "Complète : 'Je suis banni(e) du supermarché parce que...'",
    "Quel est ton nom de star du porno ? (premier animal + rue de ton enfance)",
    "Complète : 'La vraie raison de l'extinction des dinosaures était...'",
    "Décris ta vie en utilisant uniquement des titres de chansons",
    "Complète : 'À mes funérailles, ne mentionnez pas...'",
    "Quel est le titre de journal le plus absurde que tu puisses imaginer ?",
    "Complète : 'J'ai dit à mes parents que j'étudiais, mais en fait...'",
    "Invente un nouveau sport olympique",
    "Complète : 'Mes voisins pensent que je suis bizarre parce que...'",
    "Que dirait ton étiquette d'avertissement ?",
    "Complète : 'Flash info : Une personne gâche tout en...'",
    "Décris tes talents culinaires avec uniquement des titres de films d'horreur",
    "Complète : 'Je fais semblant d'être adulte, mais secrètement...'",
    "Quel est le pire nom possible pour une app de rencontres ?",
    "Complète : 'Mon historique de navigation est probablement inquiétant parce que...'",
    "Propose une suite à un film qui n'en a pas besoin",
    "Complète : 'Je pensais être séduisant(e), mais...'",
    "Quel est ton nom de super-héros basé sur ta plus grande faiblesse ?",
    "Complète : 'Les extraterrestres m'ont rendu(e) parce que...'",
    "Décris ta personnalité en utilisant uniquement de la nourriture",
    "Complète : 'Mes derniers mots seront probablement...'",
    "Quel est le pire message possible dans un biscuit chinois ?",
    "Complète : 'J'avais X ans aujourd'hui quand j'ai appris...'",
    "Invente une nouvelle phobie",
    "Complète : 'Mon autobiographie s'appellerait...'",
    "Quel est ton nom de strip-teaseuse ? (couleur préférée + dernière chose mangée)",
    "Complète : 'Je ne suis pas ivre, je suis juste...'",
    "Décris ta vie amoureuse en utilisant uniquement des chaînes de restaurants",
    "Complète : 'Mon plus grand flex c'est...'",
    "Quelle est la pire phrase de drague avec de la nourriture ?",
    "Complète : 'Recherche Google : Comment...'",
    "Propose un crossover entre deux séries complètement différentes",
    "Complète : 'Cher journal, aujourd'hui j'ai accidentellement...'",
    "Quelle est ton origine de méchant en 3 mots ?",
    "Complète : 'Plot twist : Je suis en fait...'",
    "Décris ta routine matinale en utilisant uniquement le chaos",
    "Complète : 'Instructions pas claires, j'ai fini par...'",
    "Quel est le pire thème possible pour un restaurant ?",
    "Complète : 'Mon animal spirituel est un... parce que...'",
  ],
};
