export const iceBreakers = {
  en: [
    "What superpower would you pick?",
    "Most adventurous thing you've done?",
    "Dream travel destination?",
    "Favorite movie or TV show?",
    "Which historical figure would you meet?",
    "Most unusual job you've had?",
    "Skill you wish you could master instantly?",
    "Best advice you've ever gotten?",
    "Three people for your dream dinner party?",
    "Book that changed your life?",
    "Time travel: past or future?",
    "Most memorable gift ever?",
    "Whose life would you swap for a day?",
    "Coolest place you've visited?",
    "Dream pet?",
    "Favorite childhood memory?",
    "Language you'd love to speak?",
    "Weirdest food you've tried?",
    "Fictional character you'd be?",
    "Biggest life lesson so far?",
  ],
  fr: [
    "Quel superpouvoir choisiriez-vous?",
    "Votre aventure la plus folle?",
    "Destination de rêve?",
    "Film ou émission préférée?",
    "Quel personnage historique rencontreriez-vous?",
    "Emploi le plus inhabituel?",
    "Compétence à maîtriser instantanément?",
    "Meilleur conseil reçu?",
    "Trois personnes pour un dîner idéal?",
    "Livre qui vous a marqué?",
    "Voyage dans le temps: passé ou futur?",
    "Cadeau le plus mémorable?",
    "De qui prendriez-vous la place pour une journée?",
    "Endroit le plus cool visité?",
    "Animal de compagnie idéal?",
    "Meilleur souvenir d'enfance?",
    "Langue que vous aimeriez parler?",
    "Nourriture la plus étrange essayée?",
    "Personnage de fiction que vous seriez?",
    "Plus grande leçon de vie apprise?",
  ],
};
