-- keep-alive
CREATE TABLE "keep-alive" (
  id BIGINT generated BY DEFAULT AS IDENTITY,
  name text NULL DEFAULT '':: text,
  random uuid NULL DEFAULT gen_random_uuid (),
  CONSTRAINT "keep-alive_pkey" PRIMARY key (id)
);

-- games
CREATE TABLE public.games(
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamp NOT NULL DEFAULT NOW(),
    lang text DEFAULT 'en' ::text,
    status text DEFAULT 'lobby' ::text,
    last_vote integer DEFAULT 0,
    next_vote integer DEFAULT 0,
    next_game_id uuid REFERENCES public.games ON DELETE SET NULL
);

ALTER publication supabase_realtime
    ADD TABLE public.games;

-- user profiles
CREATE TABLE public.profiles(
    id uuid PRIMARY KEY NOT NULL REFERENCES auth.users ON DELETE CASCADE,
    created_at timestamp NOT NULL DEFAULT NOW(),
    game_id uuid REFERENCES public.games ON DELETE SET NULL,
    name text
);

CREATE INDEX idx_players_profiles_id ON public.profiles(game_id);

ALTER publication supabase_realtime
    ADD TABLE public.profiles;

-- players
CREATE TABLE public.players(
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamp NOT NULL DEFAULT NOW(),
    game_id uuid NOT NULL REFERENCES public.games ON DELETE CASCADE,
    user_id uuid REFERENCES auth.users ON DELETE SET NULL,
    vote uuid REFERENCES public.players ON DELETE SET NULL,
    vote_blank boolean DEFAULT FALSE,
    is_bot boolean DEFAULT FALSE,
    score integer DEFAULT 0,
    name text
);

CREATE INDEX idx_players_game_id ON public.players(game_id);

ALTER publication supabase_realtime
    ADD TABLE public.players;

-- messages
CREATE TABLE public.messages(
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    created_at timestamp NOT NULL DEFAULT NOW(),
    game_id uuid NOT NULL REFERENCES public.games ON DELETE CASCADE,
    user_id uuid REFERENCES auth.users ON DELETE SET NULL,
    player_id uuid REFERENCES public.players ON DELETE SET NULL,
    author text,
    content text
);

CREATE INDEX idx_messages_game_id ON public.messages(game_id);

ALTER publication supabase_realtime
    ADD TABLE public.messages;

-- create a public profile when a user is created, using the same id
CREATE FUNCTION public.handle_new_user()
    RETURNS TRIGGER
    LANGUAGE plpgsql
    SECURITY DEFINER
    SET search_path = ''
    AS $$
BEGIN
    INSERT INTO public.profiles(id, name, game_id)
        VALUES(NEW.id, COALESCE(NEW.raw_user_meta_data ->> 'name', NULL), COALESCE(NEW.raw_user_meta_data ->> 'game_id', NULL)::uuid);
    RETURN new;
END;
$$;

CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW
    EXECUTE PROCEDURE public.handle_new_user();

